name: operamobile
description: A Flutter selfie editor with AI enhancement capabilities.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase and authentication - using older version to avoid app_links issue
  supabase_flutter: ^1.10.25
  
  # HTTP and networking
  http: ^1.2.2
  
  # State management
  provider: ^6.1.2
  
  # Secure storage
  flutter_secure_storage: ^9.2.4
  
  # Image handling
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  image: ^4.1.7
  path: ^1.8.3
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
