name: operamobile
description: A Flutter selfie editor with AI enhancement capabilities.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase and authentication - using older version to avoid app_links issue
  supabase_flutter: ^1.10.25
  
  # HTTP and networking
  http: ^1.2.2
  
  # State management
  provider: ^6.1.2
  
  # Secure storage
  flutter_secure_storage: ^9.2.4
  
  # Image handling
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  image: ^4.1.7
  path: ^1.8.3
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  
  # UI components
  cupertino_icons: ^1.0.2

  # Logging
  logger: ^2.0.2

  # Environment variables
  flutter_dotenv: ^6.0.0

  webview_flutter: ^4.0.7
  webview_flutter_android: ^3.16.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Development scripts
scripts:
  # Run in development mode
  dev: flutter run --dart-define=ENVIRONMENT=dev
  
  # Run in staging mode  
  staging: flutter run --dart-define=ENVIRONMENT=staging
  
  # Run in production mode
  prod: flutter run --dart-define=ENVIRONMENT=prod --release
  
  # Build for different environments
  build-dev: flutter build apk --debug --dart-define=ENVIRONMENT=dev
  build-staging: flutter build apk --debug --dart-define=ENVIRONMENT=staging
  build-prod: flutter build apk --release --dart-define=ENVIRONMENT=prod
  
  # Run tests
  test: flutter test
  
  # Analyze code
  analyze: dart analyze lib/
  
  # Clean and get dependencies
  clean: flutter clean && flutter pub get
